<script setup>
import { onMounted, ref } from 'vue'
import { api } from '../api'
const tasks=ref([]),runs=ref([]),error=ref(''),form=ref({name:'',cron:'0 9 * * 1-5',prompt:'',agent:'',provider:'',skill:'',enabled:true})
async function load(){try{tasks.value=(await api.schedules()).schedules||[];runs.value=(await api.scheduleRuns()).runs||[]}catch(e){error.value=e.message}}
async function save(){error.value='';try{await api.saveSchedule(form.value);form.value={name:'',cron:'0 9 * * 1-5',prompt:'',agent:'',provider:'',skill:'',enabled:true};await load()}catch(e){error.value=e.message}}
function edit(t){form.value={...t}}
async function del(n){if(confirm(`删除周期任务 ${n}？`)){await api.deleteSchedule(n);await load()}}
async function run(n){try{await api.runSchedule(n);await load()}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><div class="view"><header><div><h1>周期任务</h1><p class="dim">使用标准 Cron 表达式；每次执行都会记录结果。</p></div><button class="btn" @click="load">刷新</button></header><p v-if="error" class="error">{{error}}</p><section class="panel"><h2>{{form.name?'编辑任务':'新建任务'}}</h2><form @submit.prevent="save"><label>名称<input v-model="form.name" class="input" required placeholder="weekday-report"/></label><label>Cron<input v-model="form.cron" class="input mono" required/></label><label>任务提示<textarea v-model="form.prompt" class="textarea" required rows="3"/></label><label>Skill（可选）<input v-model="form.skill" class="input" placeholder="weekly-report"/></label><label><input v-model="form.enabled" type="checkbox"/> 启用</label><button class="btn primary">保存</button></form></section><section class="panel"><h2>已配置任务</h2><div v-for="t in tasks" :key="t.name" class="row"><div><b>{{t.name}}</b><span class="mono dim">{{t.cron}}</span><p>{{t.prompt}}</p></div><button class="btn" @click="run(t.name)">立即执行</button><button class="btn" @click="edit(t)">编辑</button><button class="btn danger" @click="del(t.name)">删除</button></div><p v-if="!tasks.length" class="dim">暂无周期任务。</p></section><section class="panel"><h2>执行历史</h2><div v-for="r in runs" :key="r.id" class="run"><b>{{r.task}}</b> · {{r.status}} · {{new Date(r.started_at).toLocaleString()}}<pre v-if="r.output||r.error">{{r.error||r.output}}</pre></div><p v-if="!runs.length" class="dim">暂无执行记录。</p></section></div></template>
<style scoped>.view{padding:var(--sp-6);overflow:auto;height:100%;max-width:1000px;margin:auto}header,.row{display:flex;gap:var(--sp-3);justify-content:space-between;align-items:center}h1,h2,p{margin:0}.panel{margin-top:var(--sp-5);padding:var(--sp-4);border:1px solid var(--border);border-radius:var(--radius);background:var(--surface)}form{display:grid;gap:var(--sp-3);margin-top:var(--sp-3)}label{display:grid;gap:6px}.row{padding:var(--sp-3) 0;border-bottom:1px solid var(--border)}.row span{margin-left:12px}.row p{margin-top:6px}.run{padding:var(--sp-3) 0;border-bottom:1px solid var(--border)}pre{white-space:pre-wrap;color:var(--text-dim)}.error{color:var(--danger)}</style>
