package sandbox

import (
	"fmt"
	"os"
	"os/exec"
	"syscall"

	"github.com/landlock-lsm/go-landlock/landlock"
)

// Helper is the body of the hidden HelperCommand subcommand. It applies the
// requested Landlock restrictions to itself and then execs the target, so the
// target starts already confined and never gets an unrestricted instruction. On
// success it does not return: the process image is replaced.
//
// Usage (generated by runOS, not by a human):
//
//	jelly __sandbox [--ro=PATH]… [--rw=PATH]… [--no-net] -- CMD [ARG…]
func Helper(args []string) error {
	spec, err := parseHelperArgs(args)
	if err != nil {
		return err
	}

	// Resolve the interpreter before locking down: LookPath has to walk PATH,
	// and "command not found" from inside the sandbox would be indistinguishable
	// from a policy that is merely too tight.
	path, err := exec.LookPath(spec.Cmd[0])
	if err != nil {
		return fmt.Errorf("sandbox helper: 找不到 %q: %w", spec.Cmd[0], err)
	}

	if err := restrictSelf(spec); err != nil {
		return fmt.Errorf("sandbox helper: 施加 Landlock 失败: %w", err)
	}
	return syscall.Exec(path, spec.Cmd, os.Environ())
}

// restrictSelf applies the Landlock ruleset to every thread of this process.
// Paths that do not exist on this host are ignored rather than fatal — the read
// allowlist is deliberately generous about layout (/lib64 exists on x86_64 and
// not on arm64, /opt often not at all).
func restrictSelf(spec helperSpec) error {
	var rules []landlock.Rule
	if len(spec.ReadOnly) > 0 {
		rules = append(rules, landlock.RODirs(spec.ReadOnly...).IgnoreIfMissing())
	}
	if len(spec.ReadWrite) > 0 {
		rules = append(rules, landlock.RWDirs(spec.ReadWrite...).IgnoreIfMissing())
	}

	if spec.NoNet {
		// V4 is the first ABI that handles TCP bind/connect, and handing it no
		// net rules denies both. Ask for V4 exactly first: if the kernel has it,
		// the network really is closed. Config.Restrict validates against the
		// running ABI before it enforces anything, so a refusal here leaves the
		// process untouched and the best-effort retry below is still correct.
		if err := landlock.V4.Restrict(rules...); err == nil {
			return nil
		}
	}
	// Either the mode allows the network, or this kernel is too old to restrict
	// it — confine the filesystem with whatever Landlock version is present.
	// runOS reports that shortfall to the caller rather than hiding it.
	return landlock.V4.BestEffort().RestrictPaths(rules...)
}
