-- jelly-agent · PostgreSQL 初始 schema
--
-- 对应 SQLite 版本：internal/{record,metrics,task,schedule,memory}/*.go 里的
-- schema 常量。ADK 自己的四张表（sessions / events / app_states /
-- user_states）不在这里，由 GORM AutoMigrate 建，见 README。
--
-- 要求 PostgreSQL 13+（GENERATED AS IDENTITY、gin_trgm_ops）。
--
-- 这份 DDL 和原来的 SQLite schema 几乎一一对应，这不是巧合：SQLite 的
-- UPSERT 语法本来就是抄 PostgreSQL 的，而 PG 没有 MySQL 那两条把我们逼到
-- 改结构的限制（TEXT 不能直接进索引、INSERT 子查询不能引用目标表）。
-- 差异只有四处，每处都在注释里说明。

CREATE EXTENSION IF NOT EXISTS pg_trgm;   -- 中文子串检索，contrib 自带


-- ═══ tool_results ════════════════════════════════════════════════════════
-- 工具产物。模型看到的 e1/e2 句柄就是这里的 seq。
--
-- 主键原样保留五列。PG 的 text 完全可索引、不需要前缀长度，而且 PG 不按
-- 主键聚簇——二级索引带的是 6 字节 ctid，不是整个主键。
CREATE TABLE tool_results (
  app_name      text NOT NULL,
  user_id       text NOT NULL,
  session_id    text NOT NULL,
  invocation_id text NOT NULL,
  call_id       text NOT NULL,

  -- 会话内的交付序号，模型看到的 e{seq}。由插入语句自己分配，不由调用方给：
  -- 进程内计数器一重启就会把下一轮的编号指到别的证据上，这是一个持久句柄
  -- 唯一不能出的错。
  --
  -- 分配语句（internal/record/store.go Put）在 PG 上一字不用改：
  --   INSERT INTO tool_results (...,seq,...) VALUES (...,
  --     (SELECT COALESCE(MAX(seq),0)+1 FROM tool_results WHERE ...), ...)
  --   ON CONFLICT (app_name,user_id,session_id,invocation_id,call_id)
  --   DO UPDATE SET tool=excluded.tool, ...
  -- MySQL 会以 error 1093 拒绝它（INSERT 的子查询不许引用目标表），PG 不会。
  -- 那条注释说的「One statement, so allocating the number and writing the
  -- row cannot come apart」继续成立。
  seq           bigint NOT NULL DEFAULT 0,

  tool          text NOT NULL,
  server        text NOT NULL DEFAULT '',

  -- 差异 ①：原来是 RFC3339Nano 文本，这里是真的时间类型。
  --
  -- 不是为了好看：RFC3339Nano 会砍掉末尾的零，于是整秒的
  -- "2026-09-08T10:00:00Z" 在字符串比较里排在同一秒内的
  -- "2026-09-08T10:00:00.5Z" 之后（'.' 的字节值小于 'Z'）。
  -- ORDER BY at 在秒内本来就是乱的，idx_tool_results_at 也一样。
  -- 换成 timestamptz 顺带修掉。
  at            timestamptz NOT NULL,

  bytes         bigint NOT NULL,
  sha256        text   NOT NULL,
  upstream      text   NOT NULL DEFAULT 'unknown',

  -- 差异 ②：原来用空字符串表示未过期（因为那列是 NOT NULL），这里用 NULL。
  -- 非空表示保留期已经把正文清掉了；行留着，句柄才继续解析得出来——见
  -- retention.go，这比省下的那一百字节重要得多。
  expired_at    timestamptz NULL,

  -- bytea 没有 MySQL BLOB 那个 64KB 上限（现网实测单条已 82,540 字节），
  -- 而且 substring(payload from ? for ?) 能把分段读下推到库里，
  -- read_result 翻页不用把整个产物拉回进程。
  payload       bytea NOT NULL,

  PRIMARY KEY (app_name, user_id, session_id, invocation_id, call_id)
);

CREATE UNIQUE INDEX idx_tool_results_seq
  ON tool_results (app_name, user_id, session_id, seq);
CREATE INDEX idx_tool_results_session ON tool_results (session_id);
CREATE INDEX idx_tool_results_at      ON tool_results (at);


-- ═══ tool_calls ══════════════════════════════════════════════════════════
-- 每次工具调用的耗时与结果。只写不改。
CREATE TABLE tool_calls (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at            timestamptz NOT NULL,
  session_id    text    NOT NULL DEFAULT '',
  invocation_id text    NOT NULL DEFAULT '',
  agent         text    NOT NULL DEFAULT '',
  call_id       text    NOT NULL DEFAULT '',
  tool          text    NOT NULL,
  args          text    NOT NULL DEFAULT '',
  duration_ms   bigint  NOT NULL DEFAULT 0,
  -- 差异 ③：SQLite 用 INTEGER 存布尔，PG 有真的 boolean。
  ok            boolean NOT NULL,
  err_kind      text    NOT NULL DEFAULT '',
  err           text    NOT NULL DEFAULT '',
  result_bytes  bigint  NOT NULL DEFAULT 0,
  evidence_id   text    NOT NULL DEFAULT '',
  replayed      boolean NOT NULL DEFAULT false,
  retrievable   boolean NOT NULL DEFAULT false
);

CREATE INDEX idx_tool_calls_at      ON tool_calls (at);
CREATE INDEX idx_tool_calls_session ON tool_calls (session_id);
CREATE INDEX idx_tool_calls_tool    ON tool_calls (tool);
-- SQLite 版没有这条。任务中心按 (session, invocation) 取一次运行的全部调用
-- （metrics.ByInvocation），现在只能走 session 索引再过滤。一次运行的行数
-- 不多，本地文件上无所谓；走网络就值得让索引一次带出。
CREATE INDEX idx_tool_calls_run     ON tool_calls (session_id, invocation_id);


-- ═══ task_runs ═══════════════════════════════════════════════════════════
-- 一次运行属于哪个任务。任务 id 就是 session_id + "/" + invocation_id，
-- 所以这张表本质是「续问归到哪个任务」的映射。
CREATE TABLE task_runs (
  task_id       text NOT NULL,
  session_id    text NOT NULL,
  invocation_id text NOT NULL,
  at            timestamptz NOT NULL,
  PRIMARY KEY (session_id, invocation_id)
);

CREATE INDEX idx_task_runs_task ON task_runs (task_id);


-- ═══ schedule_runs ═══════════════════════════════════════════════════════
CREATE TABLE schedule_runs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task          text NOT NULL,
  started_at    timestamptz NOT NULL,
  finished_at   timestamptz NOT NULL,
  status        text NOT NULL,
  output        text NULL,
  error         text NULL,

  -- 这两列把一次定时运行和它的步骤、产物连起来。没有它们，排程运行在控制台
  -- 里就只是一个状态加一坨文本，够不到背后的执行过程——别的表全都是按这一
  -- 对键的。
  session_id    text NOT NULL DEFAULT '',
  invocation_id text NOT NULL DEFAULT ''
);

CREATE INDEX idx_schedule_runs_task ON schedule_runs (task, started_at);
CREATE INDEX idx_schedule_runs_run  ON schedule_runs (session_id, invocation_id);


-- ═══ memory_index ════════════════════════════════════════════════════════
-- L2 会话记忆检索，替代 SQLite 的 memory_fts 虚拟表（internal/memory/fts5.go）。
--
-- 这是派生索引不是真相：AddSessionToMemory 每轮先按 session_id 删掉旧行再
-- 重建。所以换后端不涉及数据迁移，重建一遍即可。
--
-- pg_trgm 的三元分词和 FTS5 的 trigram 分词器是同一个东西，所以行为和今天
-- 完全一致，包括那个已知限制：查询要 ≥3 个字，更短的用不上索引、退化成全扫
-- （和现在退化成 LIKE 是一回事）。
--
-- 想要更好的中文分词，路是加 zhparser/pg_bigm 扩展，不必换数据库。但那是
-- 提升不是补齐——今天没人抱怨过检索质量。
CREATE TABLE memory_index (
  event_id   text NOT NULL,
  session_id text NOT NULL,
  author     text NOT NULL DEFAULT '',
  app_name   text NOT NULL,
  user_id    text NOT NULL,
  ts         timestamptz NOT NULL,
  content    text NOT NULL,

  -- 主键和访问模式对齐：重建时按 session_id 整段删除，这里正好走主键前缀，
  -- 不用额外一条索引。
  --
  -- FTS5 那张虚拟表没有任何唯一约束，所以这是一处新增的约束。它安全，是因为
  -- AddSessionToMemory 的「删掉本会话再全量插入」包在一个事务里
  -- （fts5.go:93），一个会话内的 event_id 不会重复；跨会话是 UUID，不会撞。
  PRIMARY KEY (session_id, event_id)
);

-- 子串检索走这条。GIN + gin_trgm_ops 让 content ILIKE '%查询%' 走索引。
CREATE INDEX idx_memory_index_content ON memory_index USING gin (content gin_trgm_ops);
-- 检索一律限定在一个 (app, user) 范围内。
CREATE INDEX idx_memory_index_scope   ON memory_index (app_name, user_id, ts DESC);


-- ═══ tool_decls ══════════════════════════════════════════════════════════
-- 控制台改的工具元数据。这张表是整次迁移的起因。
--
-- 之前它是一个文件（~/.jelly-agent/tools/console.yaml），界面每次保存都整
-- 文件读-改-写。后果在 2026-09-08 兑现了：一次保存把刚写进去的 suites 清空，
-- 而且没有任何历史可以查回来。多进程下还会互相丢更新——进程内那把锁跨不了
-- 进程。
--
-- 列可以为 NULL，NULL 就是「本层不声明这一项，沿用上游」。这样 patch 语义
-- 变成结构性的，而不是靠代码里的 if x != nil 维持。
--
-- 仓库里 configs/tools/*.yaml 仍然是文件：那是人手写、要 review、要进 git
-- 的基座。这张表只装界面改的覆盖层。
CREATE TABLE tool_decls (
  server        text NOT NULL DEFAULT '',
  name          text NOT NULL,

  description   text  NULL,
  use_cases     jsonb NULL,
  examples      jsonb NULL,
  anti_examples jsonb NULL,
  suites        jsonb NULL,
  produces      text  NULL,
  side_effect   text  NULL,

  updated_at    timestamptz NOT NULL,
  updated_by    text NOT NULL DEFAULT '',

  PRIMARY KEY (server, name)
);


-- ═══ tool_decl_log ═══════════════════════════════════════════════════════
-- 追加写的改动历史，兼版本号。两个用途一张表：
--
--   1. 审计——今天丢掉的正是这个。谁在什么时候把 suites 改成了什么。
--   2. 失效通知——各进程的注册表是内存态，轮询 SELECT MAX(id) 这一个整数就
--      知道要不要 reload。这同时替掉 toolreg.FileSource.Watch 那套比对文件
--      mtime 的做法，而 mtime 本来就跨不了进程。
CREATE TABLE tool_decl_log (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  server     text NOT NULL DEFAULT '',
  name       text NOT NULL,
  op         text NOT NULL,          -- upsert | delete
  -- 这次写入之后该工具的完整声明，NULL 表示删除。存快照而不是 diff：要回溯
  -- 「当时到底是什么」，快照一行就够，diff 要从头重放。
  snapshot   jsonb NULL,
  changed_at timestamptz NOT NULL,
  changed_by text NOT NULL DEFAULT ''
);

CREATE INDEX idx_tool_decl_log_tool ON tool_decl_log (server, name, id);
